# dev
FROM node:22.5.1-alpine3.20 AS dev
RUN apk add --no-cache tzdata
ENV TZ Europe/Moscow
ENV NODE_PATH /opt/client/node_modules

WORKDIR /opt/client/
COPY ./package.json ./
RUN ["npm", "i", "--legacy-peer-deps"]