FROM node:22.5.1-alpine3.20 AS builder

WORKDIR /app/client
COPY ./client .

RUN ["npm", "i", "--legacy-peer-deps"]
ARG VITE_BASE_URL
RUN echo "VITE_BASE_URL:${VITE_BASE_URL}"
RUN echo "VITE_BASE_URL${VITE_BASE_URL}" >> .env
#ENV NODE_OPTIONS=--max_old_space_size=1024
RUN ["npm", "run", "build"]

FROM nginx:1.27.0-alpine
WORKDIR /usr/share/nginx/
RUN rm -rf html && \
    mkdir html

WORKDIR /

COPY ./nginx/nginx.conf /etc/nginx
COPY --from=builder ./app/client/dist /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]